
trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
    containerRegistry: 'gcr-tutorial'
    repository: 'azure-demo-346521/clouddemo'
    kubernetesServiceConnection: 'azure-connection'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: 'Login to Container Registry'
      inputs:
        command: login
        containerRegistry: '$(containerRegistry)'
    - task: Docker@2
      displayName: Build and push image
      inputs:
        repository: '$(repository)'
        command: buildAndPush
        tags: |
          latest
        Dockerfile: 'Dockerfile'

- stage: Deploy_to_GKE
  displayName: Deploy stage
  jobs:
  - deployment: Deploy
    displayName: Deploy to GKE
    pool:
      vmImage: ubuntu-latest
    environment: azure-env
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              kubernetesServiceConnection: '$(kubernetesServiceConnection)' #service connection name
              namespace: default
              manifests: dep.yaml
