apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webapp
  name: webapp
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - image: >-
            gcr.io/azure-demo-346521/clouddemo:latest
          imagePullPolicy: Always
          name: kubernetes-deploy-tutorial-sha256-1
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: webapp
  name: webapp-service
  namespace: default
spec:
  selector:
    app: webapp
  type: LoadBalancer
  ports:
      - port: 80
        protocol: TCP
        targetPort: 5000